@extends('layouts.app')

@section('content')

    <p style="text-align:center;padding-top:10px;"><img src="{{ url("https://politicsandwar.com/uploads/abba90655c97307b46314e76e68da98008e2ff2c641.png") }}" alt="BK Flag" style="width:300px;height:150px;"></p>

    <p class="intro">Welcome to <b>Camelot</b>, a military alliance in Politics & War that boasts strong economic programs, an active community, military protection, a dash of good humor, a solid reputation as a top-ten alliance, and much more. We are happy to introduce you to our friendly, experienced members and a unique culture and unity that only <b>Camelot</b> can sorta offer. Our relaxed raiding policies and the support we can provide for national growth (regardless of size) will play a big part in your membership! Our application process, however, is very selective and we choose only the best applicants to be accepted into our alliance.</p>
    <p class="intro">After submitting your application, you will be asked a series of questions meant to judge your character, potential, and personality. If you are accepted, please keep in mind that you will be required (unless excused) to participate and graduate from <b>Avalon Academy</b> our training alliance. These educational set of modules will help prepare you and teach you not only about Politics & War, but the ideas stressed by <b>Camelot</b>, the importance of following our rules and regulations, and the duties, responsibilities, and participation that are included in your <b>Camelot</b> membership.</p>
    <p class="intro">We are <b>Camelot</b>, the carmine cavaliers, the sanguine sabers. Join us, our order, and our brotherhood, and help strike fear into the hearts of our enemies. Help us rule, help us dominate, help us pay homage to the Dank Meme Gods that judge us from the internet abyss. Become a <b>Knight</b> today!</p> <p style="text-align: center;"><a href="{{ url("https://discord.gg/9eNvpHZ") }}" class="btn btn-primary btn-lg" role="button">Apply Now</a></p>
@endsection